#!/bin/sh
if [ ! -d "build" ]; then
  mkdir build
fi

if [ ! -d "bin" ]; then
  mkdir bin
fi

cp p_list bin/
cd build

if [ ! -e CMakeCache.txt ]; then
  cmake ..
fi

make
cd ../bin
parallel < p_list
