#!/bin/bash

# control data for entire trajectory
if [ "$#" -eq 1 ] && [ -d "$1" ]; then
	mkdir "$1"/sorted/
	for file in "$1"/control_*.txt; do
		file_no=${file//[^0-9]/}
		if [ ! -f "$1"/states_$file_no.txt ] || [ ! -f "$1"/parameters_$file_no.txt ]; then
			continue
		fi
		cat "$1"/states_$file_no.txt | tr -d '[]' | tr -s ' ' '\t' | cut -f3- | tee >(head -n1 > temp1) | tail -n1 > temp2
		cat "$1"/control_$file_no.txt | tr -d '[]' | tr -s ' ' '\t' | tee >(cut -f3 | head -n -1 | tr -s "\n" "\t" > temp3) | cut -f4 | head -n -1 | tr -s "\n" "\t" > temp4
		paste temp1 temp2 temp3 temp4 | tr -s "\t" | head -c -2 >> "$1"/sorted/control_data.txt && echo >> "$1"/sorted/control_data.txt
	done
	rm temp1 temp2 temp3 temp4
	echo "Control data generated"
fi
