#!/bin/bash

# control data for entire trajectory
if [ "$#" -eq 2 ] && [ -d "$1" ]; then
	mkdir "$1"/sorted/
	for file in "$1"/control_*_$2.txt; do
		file_no=${file//[^0-9]/}
		if [ ! -f "$1"/states_${file_no}_$2.txt ] || [ ! -f "$1"/parameters_${file_no}_$2.txt ]; then
			echo "Incomplete sample" $file_no
			continue
		fi
		cat "$1"/states_${file_no}_$2.txt | tr -d '[]' | tr -s ' ' '\t' | cut -f3-6 | tee >(head -n1 > temp1) | tail -n1 > temp2
		cat "$1"/control_${file_no}_$2.txt | tr -d '[]' | tr -s ' ' '\t' | tee >(cut -f3 | head -n -1 | tr -s "\n" "\t" > temp3) | cut -f4 | head -n -1 | tr -s "\n" "\t" > temp4
		paste temp1 temp2 temp3 temp4 | tr -s "\t" | head -c -2 >> "$1"/sorted/control_data_$2.txt && echo >> "$1"/sorted/control_data_$2.txt
	done
	rm temp1 temp2 temp3 temp4
	echo "Control data generated for thread" $2
fi
